plugins:
  - jekyll-include-cache
title: adgbu GitHub Pages
description: This webpage is work in progress.
#theme: minima
#theme: jekyll-theme-minimal
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: aqua
permalink: pretty
encoding: "utf-8"
locale: "sv_SE"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true

